import Head from "next/head";

import React, { Component } from "react";

import CustomNavbar from "./components/customNavbar";
import Sipnosis from "./components/sipnosis";
import Searchbar from "./components/searchbar";
import DataSection from "./components/dataSection";
import Footer from "./components/footer";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Task 11 - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CustomNavbar />
      <Sipnosis />
      <Searchbar />
      <DataSection
        section="Characters"
        amountToShow={4}
        data={data.characters}
      />

      <DataSection section="Islands" amountToShow={3} data={data.islands} />

      <DataSection
        section="Mist Objects"
        amountToShow={4}
        data={data.mistObjects}
      />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  let islands = {};
  let characters = {};
  let mistObjects = {};

  const res = await fetch(
    "https://static.akurey.com/trainings/OnePieceInformation.json"
  );
  const data = await res.json().then((json) => {
    islands = json.islands.sort(Home.sortData);
    characters = json.characters.sort(Home.sortData);
    mistObjects = json.mysticObjects.sort(Home.sortData);
  });
  return {
    props: {
      data: {
        islands: islands,
        characters: characters,
        mistObjects: mistObjects,
      },
    },
  };
}
